- name: Install clamav
  sudo: yes
  apt: pkg=clamav state=latest

- name: Install freshclam
  sudo: yes
  apt: pkg=clamav-freshclam state=latest

- name: Install clamav daemon
  sudo: yes
  apt: pkg=clamav-daemon state=latest

- name: Restart clamav-daemon
  sudo: yes
  service: name=clamav-daemon state=restarted

- name: Copy clamav update config
  sudo: yes
  copy: src=freshclam.conf dest=/etc/clamav/freshclam.conf mode=0444

- name: Restart freshclam
  sudo: yes
  service: name=clamav-freshclam state=restarted

#- name: Set daily scan
#  sudo: yes
#  template: src=daily.j2 dest="/etc/cron.daily/clamscan" mode=0755 owner=root group=root

#- name: Set hourly scan
#  sudo: yes
#  template: src=hourly.j2 dest="/etc/cron.hourly/clamscan" mode=0755 owner=root group=root

- name: Enable and start clamav-daemon
  sudo: yes
  service: name=clamav-daemon state=started enabled=yes

- name: Enable and start freshclam
  sudo: yes
  service: name=clamav-freshclam state=started enabled=yes

- name: Update clamav
  sudo: yes
  command: freshclam --quiet
