- name: Install openssh-client
  become: yes
  apt:
    pkg: openssh-client
    state: latest

- name: Install openssh-server
  become: yes
  apt:
    pkg: openssh-server
    state: latest

- name: Replace sshd config
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -t -f %s
    backup: yes

- name: Restart sshd
  become: yes
  service:
    name: ssh
    state: restarted

- name: Enable sshd service
  become: yes
  service:
    name: ssh
    state: started
    enabled: yes

- name: Copy global SSH client config
  become: yes
  copy:
    src: ssh_config
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
