# Updates
- name: Update apt cache
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Update all packages
  sudo: yes
  apt: upgrade=dist

- name: Install unattended-upgrades
  sudo: yes
  apt: pkg=unattended-upgrades state=present

- name: Enable automatic updates
  sudo: yes
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from ubuntu release security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="{{ ubuntu_release }}-updates" state=absent

- name: Install debsums
  sudo: yes
  apt: pkg=debsums state=present

- name: Disable root account
  sudo: yes
  command: passwd -dl root

- name: Limit access to su to only admin group
  sudo: yes
  command: dpkg-statoverride --update --force --add root admin 4750 /bin/su

#- name: Remove sudo rights from group sudo
#  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent


# Set up UFW, allow only SSH
- name: UFW Default rule deny all
  sudo: yes
  ufw: policy=deny

- name: UFW Allow SSH - TCP 22 - rate limit
  sudo: yes
  ufw: rule=limit proto=tcp to_port=22

- name: UFW reload
  sudo: yes
  ufw: state=reloaded

- name: Enable ufw service
  sudo: yes
  service: name=ufw state=started enabled=yes


# Configure networking
- name: Install sysctl.conf
  sudo: yes
  copy: src=sysctl.conf dest=/etc/sysctl.conf


# Disable services
- name: Disable cups
  sudo: yes
  service: name=cups state=stopped enabled=no
  ignore_errors: yes

- name: Disable cups-browsed
  sudo: yes
  service: name=cups-browsed state=stopped enabled=no
  ignore_errors: yes

- name: Disable bluetooth
  sudo: yes
  service: name=bluetooth state=stopped enabled=no
  ignore_errors: yes

- name: Disable sane.d
  sudo: yes
  service: name=saned state=stopped enabled=no
  ignore_errors: yes

- name: Disable avahi-daemon
  sudo: yes
  service: name=avahi-daemon state=stopped enabled=no
  ignore_errors: yes

- name: Disable xinetd
  sudo: yes
  service: name=xinetd state=stopped enabled=no
  ignore_errors: yes

- name: Disable inetd
  sudo: yes
  service: name=inetd state=stopped enabled=no
  ignore_errors: yes

- name: Uninstall tftp
  sudo: yes
  apt: pkg={{ item }} state=absent
  with_items:
    - tftp-hpa
    - tftpd-hpa
    - atftp
    - atftpd
    - tftp
    - tftpd
  ignore_errors: yes

- name: Uninstall nis (ypserv)
  sudo: yes
  apt: pkg=nis state=absent
  ignore_errors: yes

- name: Uninstall telnet
  sudo: yes
  apt: pkg={{ item }} state=absent
  with_items:
    - telnet
    - inetutils-telnet
    - inetutils-telnetd
    - mactelnet-client
    - mactelnet-server
    - telnetd
    - telnet-ssl
    - telnetd-ssl
  ignore_errors: yes

- name: Uninstall RSH
  sudo: yes
  apt: pkg={{ item }} state=absent
  with_items:
    - rsh-client
    - rsh-redone-client
    - rsh-redone-server
    - rsh-server
    - sbrsh
    - sbrshd
    - xrsh
  ignore_errors: yes
