- name: Disable root account
  become: yes
  command: passwd -dl root

- name: Limit access to su to only admin group
  become: yes
  command: dpkg-statoverride --update --force --add root admin 4750 /bin/su

#- name: Remove sudo rights from group sudo
#  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent

# Configure networking
- name: Install sysctl.conf
  become: yes
  copy: src=sysctl.conf dest=/etc/sysctl.conf

# Disable services
- name: Disable cups
  become: yes
  service: name=cups state=stopped enabled=no
  ignore_errors: yes

- name: Disable cups-browsed
  become: yes
  service: name=cups-browsed state=stopped enabled=no
  ignore_errors: yes

- name: Disable bluetooth
  become: yes
  service: name=bluetooth state=stopped enabled=no
  ignore_errors: yes

- name: Disable sane.d
  become: yes
  service: name=saned state=stopped enabled=no
  ignore_errors: yes

- name: Disable avahi-daemon
  become: yes
  service: name=avahi-daemon state=stopped enabled=no
  ignore_errors: yes

- name: Disable xinetd
  become: yes
  service: name=xinetd state=stopped enabled=no
  ignore_errors: yes

- name: Disable inetd
  become: yes
  service: name=inetd state=stopped enabled=no
  ignore_errors: yes

- name: Uninstall tftp
  become: yes
  apt: pkg={{ item }} state=absent
  with_items:
    - tftp-hpa
    - tftpd-hpa
    - atftp
    - atftpd
    - tftp
    - tftpd
  ignore_errors: yes

- name: Uninstall nis (ypserv)
  become: yes
  apt: pkg=nis state=absent
  ignore_errors: yes

- name: Uninstall telnet
  become: yes
  apt: pkg={{ item }} state=absent
  with_items:
    - telnet
    - inetutils-telnet
    - inetutils-telnetd
    - mactelnet-client
    - mactelnet-server
    - telnetd
    - telnet-ssl
    - telnetd-ssl
  ignore_errors: yes

- name: Uninstall RSH
  become: yes
  apt: pkg={{ item }} state=absent
  with_items:
    - rsh-client
    - rsh-redone-client
    - rsh-redone-server
    - rsh-server
    - sbrsh
    - sbrshd
    - xrsh
  ignore_errors: yes
