- name: Download the govc gz
  get_url: url=https://github.com/vmware/govmomi/releases/download/v0.8.0/govc_linux_amd64.gz
           dest=/tmp/govc_linux_amd64.gz
           checksum=sha1:367ce7e96126214ab76af22376eacdccb31dc869

- name: Uncompress govc
  become: yes
  command: gzip -d /tmp/govc_linux_amd64.gz

- name: chmod +x govc
  become: yes
  file: path=/tmp/govc_linux_amd64
        state=file
        mode=0755

- name: Install govc
  become: yes
  command: mv /tmp/govc_linux_amd64 /usr/local/bin/govc
