- debug: var=vars
- debug: var=hostvars[inventory_hostname]

- name: Remove CD source
  become: yes
  replace: dest=/etc/apt/sources.list regexp='^deb cdrom:' replace='# deb cdrom:'

- name: Update apt cache
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Update all packages
  become: yes
  apt: upgrade=dist state=latest

- name: Install system packages
  become: yes
  apt:
    pkg: ['curl',
          'debsums',
          'ntp',
          'software-properties-common',
          'sudo',
          'sysstat',
          'tmux',
          'ufw',
          'unzip',
          'vim',
          'whois',
          'zip']
    state: latest

- name: Enable and start NTP service
  become: yes
  service: name=ntp state=started enabled=yes