- name: Set hostname
  sudo: yes
  hostname: name={{ hostname }}

- name: Update /etc/hosts
  sudo: yes
  lineinfile: dest=/etc/hosts regexp='^127.0.1.1' line='127.0.1.1 {{ hostname }}'

- name: Update apt cache
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Update all packages
  sudo: yes
  apt: upgrade=dist

- name: Install system packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mosh
    - ntp
    - sudo
    - sysstat
    - tmux
    - unzip
    - vim
    - zip

- name: Enable and start NTP service
  sudo: yes
  service: name=ntp state=started enabled=yes
