- name: Install neovim repository
  become: yes
  apt_repository: repo='ppa:neovim-ppa/stable' update_cache=yes mode=0644

- name: Install neovim
  become: yes
  apt:
    pkg: neovim
    state: latest