- name: "Install Atom apt key"
  become: yes
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present

- name: "Install Atom repo"
  become: yes
  command: sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'

- name: "Install Atom"
  become: yes
  apt:
    name: atom
    state: latest
    update_cache: yes
