- name: Get Docker install script
  get_url: url=https://get.docker.com/ dest=/tmp/install_docker.sh mode=0755

- name: Install Docker
  become: yes
  shell: /tmp/install_docker.sh

- name: Add non-root user to docker group
  become: yes
  command: usermod -aG docker {{ ansible_user_id }}
