- name: "Make tbb directory"
  become: yes
  file:
    path: /opt/tbb
    state: directory
    mode: 0775
    owner: "{{ ansible_env.USERNAME }}"
    group: "{{ ansible_env.USERNAME }}"

- name: "Get Tor Browser"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.0.1/tor-browser-linux64-9.0.1_en-US.tar.xz"
    checksum: sha256:a5f45b02a59cb84f936b06a64a7bb71cf54c38e7c4f6fb7c0b6d583e82d42a26
    dest: "/opt/tbb/tor-browser-linux64.tar.xz"

- name: "Get Tor Browser Signature"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.0.1/tor-browser-linux64-9.0.1_en-US.tar.xz.asc"
    checksum: sha256:9f9eca3e9b2adbf7fb125a6b42db944c49a2d109ed3143598817537bfd95a672
    dest: "/opt/tbb/tor-browser-linux64.tar.xz.asc"

- name: "Get GPG Key"
  command: "gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org"
  # command: "gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290"

- name: "Show fingerprint"
  command: "gpg --fingerprint 0x4E2C6E8793298290"

- name: "Verify Signature"
  command: "gpg --verify /opt/tbb/tor-browser-linux64.tar.xz.asc"
  register: sig_result

- debug:
    msg: "{{ sig_result.stdout }}"
    msg: "{{ sig_result.stderr }}"

- name: "Fail on bad signature"
  fail:
    msg: "Failed to verify signature"
  when: sig_result.rc != 0

- name: "Unarchive TBB"
  command: "unxz /opt/tbb/tor-browser-linux64.tar.xz"

- name: "Unarchive TBB"
  command: "tar -C /opt/tbb/ -xf /opt/tbb/tor-browser-linux64.tar"
