- name: "Make tbb directory"
  become: yes
  file:
    path: /opt/tbb
    state: directory
    mode: 0775
    owner: "{{ ansible_env.USERNAME }}"
    group: "{{ ansible_env.USERNAME }}"

- name: "Get Tor Browser"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.5.3/tor-browser-linux64-9.5.3_en-US.tar.xz"
    checksum: sha256:648931503b886d687828df9730aa284b7c18303682cc82f06c9da4a734c81bcf
    dest: "/opt/tbb/tor-browser-linux64.tar.xz"

- name: "Get Tor Browser Signature"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.5.3/tor-browser-linux64-9.5.3_en-US.tar.xz.asc"
    checksum: sha256:0a87c92ec35d1b4d871a982a87ca3d9e58c037243edf79af8095678aedeb7bec
    dest: "/opt/tbb/tor-browser-linux64.tar.xz.asc"

#- name: "Get GPG Key"
#  command: "gpg2 --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290"
#  command: "gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org"

- name: "Copy GPG Key"
  copy:
    src: key
    dest: /tmp/tor-key
    mode: 0644
    owner: "{{ ansible_env.USERNAME }}"
    group: "{{ ansible_env.USERNAME }}"

- name: "Import GPG Key"
  command: "gpg2 --import /tmp/tor-key"

- name: "Show fingerprint"
  command: "gpg2 --fingerprint 0x4E2C6E8793298290"

- name: "Verify Signature"
  command: "gpg2 --verify /opt/tbb/tor-browser-linux64.tar.xz.asc"
  register: sig_result

- debug:
    msg: "{{ sig_result.stdout }}"
    msg: "{{ sig_result.stderr }}"

- name: "Fail on bad signature"
  fail:
    msg: "Failed to verify signature"
  when: sig_result.rc != 0

- name: "Unarchive TBB"
  command: "unxz /opt/tbb/tor-browser-linux64.tar.xz"

- name: "Unarchive TBB"
  command: "tar -C /opt/tbb/ -xf /opt/tbb/tor-browser-linux64.tar"
