- name: "Make tbb directory"
  become: yes
  file:
    path: /opt/tbb
    state: directory
    mode: 0775
    owner: "{{ ansible_env.USERNAME }}"
    group: "{{ ansible_env.USERNAME }}"

- name: "Get Tor Browser"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.0.4/tor-browser-linux64-9.0.4_en-US.tar.xz"
    checksum: sha256:53c85059445eff023e7e5ed4749dfdf12b328353e82a4c7263f010120570f493
    dest: "/opt/tbb/tor-browser-linux64.tar.xz"

- name: "Get Tor Browser Signature"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.0.4/tor-browser-linux64-9.0.4_en-US.tar.xz.asc"
    checksum: sha256:7b3a5790bac8d11d208adea7b87f88f3900aff9e4dd1e77d11582f7973a344d5
    dest: "/opt/tbb/tor-browser-linux64.tar.xz.asc"

- name: "Get GPG Key"
  command: "gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org"
  # command: "gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290"

- name: "Show fingerprint"
  command: "gpg --fingerprint 0x4E2C6E8793298290"

- name: "Verify Signature"
  command: "gpg --verify /opt/tbb/tor-browser-linux64.tar.xz.asc"
  register: sig_result

- debug:
    msg: "{{ sig_result.stdout }}"
    msg: "{{ sig_result.stderr }}"

- name: "Fail on bad signature"
  fail:
    msg: "Failed to verify signature"
  when: sig_result.rc != 0

- name: "Unarchive TBB"
  command: "unxz /opt/tbb/tor-browser-linux64.tar.xz"

- name: "Unarchive TBB"
  command: "tar -C /opt/tbb/ -xf /opt/tbb/tor-browser-linux64.tar"
