- name: "Make tbb directory"
  become: yes
  file:
    path: /opt/tbb
    state: directory
    mode: 0775
    owner: "{{ ansible_env.USERNAME }}"
    group: "{{ ansible_env.USERNAME }}"

- name: "Get Tor Browser"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.0.9/tor-browser-linux64-9.0.9_en-US.tar.xz"
    checksum: sha256:cf910b9577dc94bcfeef60fe9904e7f8f29277bf1a7360600c32956225d04473
    dest: "/opt/tbb/tor-browser-linux64.tar.xz"

- name: "Get Tor Browser Signature"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/9.0.9/tor-browser-linux64-9.0.9_en-US.tar.xz.asc"
    checksum: sha256:b941c73530c50a0e999efb357e2086f03c8f95236833b11e1ccfe94d1da5d488
    dest: "/opt/tbb/tor-browser-linux64.tar.xz.asc"

- name: "Get GPG Key"
  command: "gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org"
  # command: "gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290"

- name: "Show fingerprint"
  command: "gpg --fingerprint 0x4E2C6E8793298290"

- name: "Verify Signature"
  command: "gpg --verify /opt/tbb/tor-browser-linux64.tar.xz.asc"
  register: sig_result

- debug:
    msg: "{{ sig_result.stdout }}"
    msg: "{{ sig_result.stderr }}"

- name: "Fail on bad signature"
  fail:
    msg: "Failed to verify signature"
  when: sig_result.rc != 0

- name: "Unarchive TBB"
  command: "unxz /opt/tbb/tor-browser-linux64.tar.xz"

- name: "Unarchive TBB"
  command: "tar -C /opt/tbb/ -xf /opt/tbb/tor-browser-linux64.tar"
