- name: "Make tbb directory"
  become: yes
  file:
    path: /opt/tbb
    state: directory
    mode: 0775
    owner: "{{ ansible_env.USERNAME }}"
    group: "{{ ansible_env.USERNAME }}"

- name: "Get Tor Browser"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/8.5.4/tor-browser-linux64-8.5.4_en-US.tar.xz"
    checksum: sha256:df248f7751b8bff862c761dab3a1502557ab92864f4ac40e41cd523ba6f5df5a
    dest: "/opt/tbb/tor-browser-linux64.tar.xz"

- name: "Get Tor Browser Signature"
  get_url:
    url: "https://www.torproject.org/dist/torbrowser/8.5.4/tor-browser-linux64-8.5.4_en-US.tar.xz.asc"
    checksum: sha256:020b6f10bac58b686724d47cd798144e8c7dece35a8c5ef44cc2e33f00554190
    dest: "/opt/tbb/tor-browser-linux64.tar.xz.asc"

- name: "Get GPG Key"
  command: "gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org"
  # command: "gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290"

- name: "Show fingerprint"
  command: "gpg --fingerprint 0x4E2C6E8793298290"

- name: "Verify Signature"
  command: "gpg --verify /opt/tbb/tor-browser-linux64.tar.xz.asc"
  register: sig_result

- debug:
    msg: "{{ sig_result.stdout }}"
    msg: "{{ sig_result.stderr }}"

- name: "Fail on bad signature"
  fail:
    msg: "Failed to verify signature"
  when: sig_result.rc != 0

- name: "Unarchive TBB"
  command: "unxz /opt/tbb/tor-browser-linux64.tar.xz"

- name: "Unarchive TBB"
  command: "tar -C /opt/tbb/ -xf /opt/tbb/tor-browser-linux64.tar"
