- name: Install unattended-upgrades
  sudo: yes
  apt: pkg=unattended-upgrades state=present

- name: Install update-notifier-common
  sudo: yes
  apt: pkg=update-notifier-common state=present
  when: unattended_reboot

- name: Configure apt auto-upgrades
  sudo: yes
  copy: src=20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades owner=root group=root mode=0644

- name: Configure unattended-upgrades
  sudo: yes
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=0644
