- name: Install KVM
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
  - qemu-kvm
  - libvirt-bin
  - bridge-utils

- name: Install X2Go repository
  become: yes
  apt_repository: repo='ppa:x2go/stable' update_cache=yes mode=0644

- name: Install X2Go
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - x2goserver
    - x2goserver-xsession

- name: Install xfce desktop
  become: yes
  apt: name=xfce4 state=latest
  when: remote
