- name: Install KVM
  become: yes
  apt:
    pkg: ['qemu-kvm', 'libvirt-bin', 'bridge-utils']
    state: latest

- name: Install X2Go repository
  become: yes
  apt_repository: repo='ppa:x2go/stable' update_cache=yes mode=0644

- name: Install X2Go
  become: yes
  apt:
    pkg: ['x2goserver', 'x2goserver-xsession']
    state: latest

- name: Install xfce desktop
  become: yes
  apt: name=xfce4 state=latest
  when: remote