- name: Create vim colors dir
  file: path="~/.vim/colors" state=directory

- name: Install vim solarized colors
  copy: src=solarized.vim dest="~/.vim/colors/solarized.vim" mode=0644

- name: Install vim
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - vim

- name: Install exuberant-ctags (for vim taglist)
  become: yes
  apt: pkg=exuberant-ctags state=latest

