- name: Remove unnecessary users
  sudo: yes
  user: name={{ item }} state=absent
  with_items:
    - games
    - gnats
    - irc
    - list
    - news
    - proxy
    - uucp

- name: Set shell to nologin for users
  sudo: yes
  user: name={{ item }} shell=/usr/sbin/nologin
  with_items:
    - daemon
    - bin
    - lp
    - sys
    - man
    - mail
    - backup
    - nobody
    - libuuid

- name: Remove unnecessary groups
  sudo: yes
  group: name={{ item }} state=absent
  with_items:
    - news
    - uucp
    - proxy
    - list
    - irc
    - src
    - gnats
    - games
