- name: Install python
  apt:
    pkg:  ['python3-setuptools', 'python3-pip', 'python3', 'python3-dev']
    state: latest
  become: yes

- name: Install python packages
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - pip
    - awscli
    - boto
    - flake8
    - ipdb
    - pylint
    - virtualenv
