- name: Add nginx apt key
  become: yes
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Add nginx repo
  become: yes
  lineinfile: >
    dest=/etc/apt/sources.list
    line="deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"

- name: Update apt cache
  become: yes
  apt: update_cache=yes

- name: Install nginx
  become: yes
  apt:
    pkg: nginx
    state: latest

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started
