- name: Reboot
  sudo: yes
  command: shutdown -r now
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for boot
  sudo: no
  local_action: wait_for host={{ item }}
                port={{ ssh_port }}
                state=started
  with_items: groups['{{ reboot_hosts }}']
