- name: "Install golang repo"
  sudo: yes
  apt_repository: repo="ppa:ubuntu-lxc/lxd-stable"

- name: "Install golang"
  sudo: yes
  apt: name=golang update_cache=yes

- name: "Create go directory"
  file: path={{ ansible_env.HOME }}/go state=directory mode=0755
