- name: Download the Go tarball
  get_url: url=https://storage.googleapis.com/golang/go1.6.3.linux-amd64.tar.gz
           dest=/tmp/go1.6.3.linux-amd64.tar.gz
           checksum=sha256:cdde5e08530c0579255d6153b08fdb3b8e47caabbe717bc7bcd7561275a87aeb

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Extract the Go tarball if Go is not yet installed or not the desired version
  become: yes
  unarchive: src=/tmp/go1.6.3.linux-amd64.tar.gz
             dest=/usr/local
             copy=no

- name: "Create go directory"
  file: path={{ ansible_env.HOME }}/go/src/github.com state=directory mode=0755
