- name: "Install golang repo"
  sudo: yes
  apt_repository: repo="ppa:ubuntu-lxc/lxd-stable" mode=0644

- name: "Install golang"
  sudo: yes
  apt: name=golang update_cache=yes

- name: "Create go directory"
  file: path={{ ansible_env.HOME }}/go/src/github.com state=directory mode=0755
