- name: Install chkrootkit
  sudo: yes
  apt: pkg=chkrootkit state=latest

- name: Schedule daily chkrootkit report
  sudo: yes
  cron: name="chkrootkit report" minute="0" hour="0" job="chkrootkit > /var/log/chkrootkit.log 2>&1"

- name: Copy chkrootkit logrotation configuration
  sudo: yes
  copy: src=logrotate-chkrootkit.conf dest=/etc/logrotate.d/chkrootkit owner=root group=root mode=644

- name: Copy chkrootkit cron logrotation configuration
  sudo: yes
  copy: src=logrotate-chkrootkit-cron.conf dest=/etc/logrotate.d/chkrootkit-cron owner=root group=root mode=644
