- name: Install nut package
  become: yes
  apt: pkg=nut state=latest

- name: Configure nut mode
  become: yes
  lineinfile: >
    dest=/etc/nut/nut.conf
    regexp="^MODE=none"
    line="MODE=netclient"
    state=present

- name: Configure upsmon
  become: yes
  lineinfile: >
    dest=/etc/nut/upsmon.conf
    line="MONITOR {{ ups_name }}@{{ ups_ip }} 1 {{ ups_user }} {{ ups_password }} slave"
    state=present

- name: Restart nut-client
  become: yes
  service: name=nut-client state=restarted

# upsc <ups_name>@<ups_ip>
