- name: Install dev tools
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - ack-grep
    - build-essential
    - git
    - python
    - python-dev
    - python-pip
    - python-software-properties
    - python-support

- name: Create github directory
  file: path={{ ansible_env.HOME }}/github state=directory mode=0755
