- name: Install networking packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - dnsutils
    - lynx
    - openssh-client
    - openssh-server
    - ngrep
    - rsync
    - tcpdump
    - traceroute

- name: Disable rsync service
  sudo: yes
  service: name=rsync state=stopped enabled=no
