- name: Enable UFW with default reject
  sudo: yes
  ufw: state=enabled direction=incoming policy=reject log=yes

- name: Enable UFW logging
  sudo: yes
  ufw: logging=on

- name: Allow SSH rate limited
  sudo: yes
  ufw: rule=limit port={{ ssh_port }} proto=tcp
