- name: Enable UFW with default deny
  sudo: yes
  ufw: state=enabled policy=deny

- name: Enable logging
  sudo: yes
  ufw: logging=on

- name: Allow SSH 22/tcp
  sudo: yes
  ufw: rule=allow port=22 proto=tcp
