- name: Install server packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - smartmontools
    - rng-tools

- name: Install livepatch
  become: yes
  snap:
    name: canonical-livepatch
    state: present