- name: Get Docker client 1.13
  get_url:
    url: https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz
    dest: /tmp/docker-1.13.1.tgz
    mode: 0644
    checksum: sha256:97892375e756fd29a304bd8cd9ffb256c2e7c8fd759e12a55a6336e15100ad75

- name: Install Docker client in /usr/local/bin
  become: yes
  unarchive:
    src: /tmp/docker-1.13.1.tgz
    dest: /usr/local/bin
