---
- name: Install Tiddlywiki.
  hosts: all
  gather_facts: yes

  roles:
    - common
    - ufw
    - ssh
    - nodejs
    - tiddlywiki
    # - tiddlywiki-start
    # - tiddlywiki-nginx
    # - tiddlywiki-ufw
