---
- name: Install Tiddlywiki.
  hosts: all
  gather_facts: yes

  roles:
    #- common
    #- ssh
    - nodejs
    - tiddlywiki
    # - tiddlywiki-start
    # - tiddlywiki-nginx
    # - tiddlywiki-ufw
