---
- name: Configure Ubuntu Server as webserver.
  hosts: all
  gather_facts: yes

  roles:
    - common
    - ssh
    - ufw
    - nginx
    - nginx-conf-static
    - lets-encrypt
    - user
    - authorized-keys
    - passwordless-sudo
