---
- import_playbook: common.yml

- name: Configure Ubuntu Browsing VM.
  hosts: all
  gather_facts: yes

  roles:
    - desktop-utils
    - remap-esc
    - chrome
    - firefox
    - tor-browser
    - pwgen
    - open-vm-tools-desktop