---
- include: common.yml

- name: Configure Ubuntu Desktop.
  hosts: all
  gather_facts: yes

  roles:
    # TODO fix
    #    - desktop-apt
    - remap-esc
    - chrome
    - firefox
    - unity-cleanup
