---
- name: Configure Ubuntu Server as webserver.
  hosts: all
  gather_facts: yes

  roles:
    - common
    - ufw
    - user
    - authorized-keys
    - passwordless-sudo
    - unattended-upgrades
    - nginx
    - nginx-conf-static
    - lets-encrypt
    - lets-encrypt-nginx
    - ssh
