---
- name: Configure Ubuntu Desktop.
  hosts: all
  gather_facts: yes

  roles:
    - common
    - rcm
    - set-hostname
    - solarized
    - ssh
    - ufw
    - vim
    - desktop
    - chrome
    - firefox
    - unity-cleanup
