---
- name: Developer tools for VMware.
  hosts: all
  gather_facts: yes

  roles:
    - dev-directory
    - developer-tools-apt
    - docker
    - docker-systemd-vmware
    - emacs
    - golang
    - { role: set-hostname,  set_hostname: "CORPORATE" }
