---
- include: developer.yml

- name: VMware work customizations.
  hosts: all
  gather_facts: yes

  roles:
    - docker
    - docker-version-manager
    - docker-systemd-vmware
    - docker-compose
    - dronecli
    - gosudo
    - govc
    - delve
    - gotools
    - cfssl
    - robotframework
    - asciinema
    - disable-idle-screen
    - gcloud
