- name: Disable IPv6
  sudo: yes
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1

- name: Disable IPv6
  sudo: yes
  sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1

- name: Disable IPv6
  sudo: yes
  sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1
